name: Publish CLI on Npm

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install stuff
        run: npm i

      - name: Build package
        run: make

      - name: Publish to NPM
        run: |
          npx dotenv -- npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}